### ISSUE TITLE
Just want to check the roadmap

### ISSUE THREAD

**Issue by grizzly-monkey** [processone/eimp#1]
@zinid  Do we also have plans for 
1) Image cropping / rotate / resize  
2) Extract image from Video 
3) Where will this dep used in ejabberd  

I know its just a day old dep but i am super exicited for using.
I have already started using it will report if i find any bugs.

Also why are we using GD  any specific reason? from all the tests over the web GrapicsMagick is fastest later ImageMagick and the SLOWEST of all is GD ...

**Comment by zinid** [comment]
The current usage will be to convert WebP avatars, because Conversations uses them, while other clients don't support WebP at all.
But image resizing and captcha generation is on roadmap (to avoid calls to imagemagick commands).

**Comment by grizzly-monkey** [comment]
Cannot convert png to jpeg properly.

 erl -pa ebin/ deps/p1_utils/ebin/
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

```
Eshell V8.2.1  (abort with ^G)
1> eimp:start().
ok
2> {ok,Data} = file:read_file("/home/glabbr/Pictures/menu_broadcast.png").
{ok,<<137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,
      0,72,0,0,0,72,8,6,0,...>>}
6> {ok,Jpeg} = eimp:convert(Data,jpeg).                             
{ok,<<255,216,255,224,0,16,74,70,73,70,0,1,1,1,0,96,0,96,
      0,0,255,254,0,62,67,82,69,...>>}
7> 
7> file:write_file("/home/glabbr/Pictures/menu_broadcast.jpg",Jpeg).
ok

```


![menu_broadcast](https://user-images.githubusercontent.com/6825834/30325314-cc048ea8-97b3-11e7-9e2e-c9888bdd6470.jpg)
![menu_broadcast](https://user-images.githubusercontent.com/6825834/30325315-cc0822b6-97b3-11e7-9d9b-fedb4f97cd23.png)


Above are attached white images 
https://user-images.githubusercontent.com/6825834/30325314-cc048ea8-97b3-11e7-9e2e-c9888bdd6470.jpg

https://user-images.githubusercontent.com/6825834/30325315-cc0822b6-97b3-11e7-9d9b-fedb4f97cd23.png

**Comment by grizzly-monkey** [comment]
> (to avoid calls to imagemagick commands).
i was trying to say instead of using gd port can we not use imagemagick port  ? as gd is slower

**Comment by zinid** [comment]
How gd is slower? It uses libpng/libjpg/libwebp.

**Comment by zinid** [comment]
Regarding your images, I just tried imagemagick's `convert` program and it produces the same result (i.e. blank white jpeg).

**Comment by grizzly-monkey** [comment]
@zinid  my miss you are right as always :) the problem was with image will be more careful next time before opening one .. 

> How gd is slower? It uses libpng/libjpg/libwebp.
i was reading over web with imagemagick vs gd benchmark and found gd was slower 
but it does make sense that you are using gd using   libpng/libjpg/libwebp so it may not affect performance as such
