### ISSUE TITLE
eimp:is_supported/1 returns false for any type

### ISSUE THREAD

**Issue by AndriiKlymchuk** [processone/eimp#10]
Hello, I have a trouble with using library: function eimp:is_supported/1 returns false for any type

Here is my setup:
OS: Ubuntu 16.04.3 LTS
libjpeg: libjpeg-dev/xenial,now 8c-2ubuntu8 amd64 [installed]
libgd: libgd-dev/xenial-updates,xenial-security,now 2.1.1-4ubuntu0.16.04.11 amd64 [installed]
libpng: libpng12-dev/xenial-updates,xenial-security,now 1.2.54-1ubuntu1.1 amd64 [installed]
libwebp: libwebp-dev/xenial,now 0.4.4-1 amd64 [installed]
erlang: esl-erlang/unknown,now 1:21.3.2-1 amd64 [installed,upgradable to: 1:21.3.3-1]

Could you please help me to debug this issue?

**Comment by zinid** [comment]
Did you run ./configure?

**Comment by AndriiKlymchuk** [comment]
It helped, thanks. I use eimp as a dependency in my rebar3 project. Should rebar3 run configure inside eimp directory by itself when compiling dependencies?

**Comment by AndriiKlymchuk** [comment]
Sorry, I misunderstood README, I should add pre-hook by myself in my rebar.config. Thank you!
