### ISSUE TITLE
How to add rebar3 pre-hook to run configure script before compilation?

### ISSUE THREAD

**Issue by AndriiKlymchuk** [processone/eimp#11]
Hi. My rebar3 project uses eimp as dependency. I tried to add 
`{pre_hooks, [{compile, "sh ${REBAR_DEPS_DIR}/eimp/configure"}]}`. 
to my rebar.config in order to run configure script before eimp compilation, but rebar3 run this hook after all deps compilation and before main application compilation. How can I add the hook in my rebar.config so that it will be called before eimp compilation?

**Comment by weiss** [comment]
As per the [rebar3 documentation][1] (but I didn't test myself):

```erlang
{overrides, [{add, eimp, [{pre_hooks, [{compile, "[...]"}]}]}]}.
```

[1]: https://www.rebar3.org/docs/configuration
