### ISSUE TITLE
How to extend eimp

### ISSUE THREAD

**Issue by grizzly-monkey** [processone/eimp#2]
@zinid 
I was trying to extend eimp to scale (resize) and crop for this  i found 
gdImageScale
gdImageCrop
gdImageCropAuto functions
https://libgd.github.io/manuals/2.2.4/files/gd_interpolation-c.html#gdImageScale
https://libgd.github.io/manuals/2.2.5/files/gd_crop-c.html#Cropping

However i see in eimp.c 
main () calls loop (void) and it calls only convert()
How do extend / change so that i can also add other gd function support.

did not quite understand 
```
if (buf) {
	  if (read_buf(buf, size) == size) {
	    pid_size = buf[0];
	    if (size >= pid_size + 3) {
	      result = convert(buf, buf[pid_size + 1], buf[pid_size + 2],
			       buf+pid_size+3, size-pid_size-3);
	    }
	  }
	}
```

**Comment by zinid** [comment]
Wait a bit, I will add new command (`identify`) and will improve this C crap :smile:

**Comment by grizzly-monkey** [comment]
Cool thanks @zinid

**Comment by zinid** [comment]
I've just added `identify/1` function (see README).
I also added description of the data format accepted by the port (see c_src/eimp.c comments).
Let me know if you have further questions.

**Comment by zinid** [comment]
Scaling is also added, see [README.md](https://github.com/processone/eimp/blob/master/README.md)

**Comment by grizzly-monkey** [comment]
Great ... @zinid thanks ..
Will try to extend this to other functions Thanks for quick turnaround.
